import 'package:flutter/material.dart';

class AppColorScheme {
  static const ColorScheme lightColorScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFFFCD40),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF2C2C2C),
    onPrimaryContainer: Color(0xFFFFFFFF),
    secondary: Color(0xFF13A4F3),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE3E3E7),
    onSecondaryContainer: Color(0xFF000000),
    tertiary: Color(0xFFFC5C67),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFEAF5E7),
    onTertiaryContainer: Color(0xFF1E9D00),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF1C1C1C),
    surfaceContainerHighest: Color(0xFF49454F),
    onSurfaceVariant: Color(0xFF49454F),
    outline: Color(0xFF79747E),
    onInverseSurface: Color(0xFFF1F1F1),
    inverseSurface: Color(0xFF2C2C2C),
    inversePrimary: Color(0xFF37D39A),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF13562E),
    outlineVariant: Color(0xFFC4C7C5),
    scrim: Color(0xFF000000),
  );

  static const ColorScheme darkColorScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFFFFCD40),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFF2C2C2C),
    onPrimaryContainer: Color(0xFFFFFFFF),
    secondary: Color(0xFF5F64EB),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFE3E3E7),
    onSecondaryContainer: Color(0xFF000000),
    tertiary: Color(0xFFFC5C67),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFEAF5E7),
    onTertiaryContainer: Color(0xFF1E9D00),
    error: Color(0xFFBA1A1A),
    errorContainer: Color(0xFFFFDAD6),
    onError: Color(0xFFFFFFFF),
    onErrorContainer: Color(0xFF410002),
    surface: Color(0xFFFFFFFF),
    onSurface: Color(0xFF1C1C1C),
    surfaceContainerHighest: Color(0xFF49454F),
    onSurfaceVariant: Color(0xFF49454F),
    outline: Color(0xFF79747E),
    onInverseSurface: Color(0xFFF1F1F1),
    inverseSurface: Color(0xFF2C2C2C),
    inversePrimary: Color(0xFF37D39A),
    shadow: Color(0xFF000000),
    surfaceTint: Color(0xFF13562E),
    outlineVariant: Color(0xFFC4C7C5),
    scrim: Color(0xFF000000),
  );
}
